import Link from 'next/link'
import React from 'react'

const page = () => {
    return (
        <div className='overflow-hidden h-full'>

            <section className='w-full flex items-center justify-start flex-col bg-[#fbfbfb] mt-10 max-w-[1800px] mb-[60px]  px-[30px] lg:px-[60px] xll:px-[120px] py-[4rem] mx-auto'>
                <h1 className='text-center mb-[20px] font-poppins text-[30px] xsm:text-[40px] lg:text-[55px] xll:text-[60px] font-[500] text-[#3d3d3d]'>
                Privacy Policy
                </h1>


                <div className='privacy-text'>
                <h2 className=" text-2xl xsm:text-3xl sm:text-4xl text-left font-poppins text-[#222] mb-3">
                    Privacy Policy</h2>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Your privacy is important to us. It is Reborngreen Ltd&#39;s policy to respect your privacy and comply with any applicable law and regulation regarding any personal information we may collect about you, including across our website, <Link href="https://reborngreen.org">https://reborngreen.org</Link>, and other sites we own and operate.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Personal information is any information about you which can be used to identify you. This includes information about you as a person (such as name, address, and date of birth), your devices, payment details, and even information about how you use a website or online service.</p>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>In the event our site contains links to third-party sites and services, please be aware that those sites and services have their own privacy policies. After following a link to any third-party content, you should read their posted privacy policy information about how they collect and use personal information. This Privacy Policy does not apply to any of your activities after you leave our site.</p>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>This policy is effective as of March 31, 2024</p>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Last updated: March 31, 2024</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Information We Collect</h3>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Information we collect falls into one of two categories: “voluntarily provided” information and “automatically collected” information.</p>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>“Voluntarily provided” information refers to any information you knowingly and actively provide us when using or participating in any of our services and promotions.</p>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>“Automatically collected” information refers to any information automatically sent by your devices in the course of accessing our products and services.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Log Data</h3>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When you visit our website, our servers may automatically log the standard data provided by your web browser. It may include your device’s Internet Protocol (IP) address, your browser type and version, the pages you visit, the time and date of your visit, the time spent on each page, and other details about your visit.</p>
                    <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Additionally, if you encounter certain errors while using the site, we may automatically collect data about the error and the circumstances surrounding its occurrence. This data may include technical details about your device, what you were trying to do when the error happened, and other technical information relating to the problem. You may or may not receive notice of such errors, even in the moment they occur, that they have occurred, or what the nature of the error is.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Please be aware that while this information may not be personally identifying by itself, it may be possible to combine it with other data to personally identify individual persons.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Device Data</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When you visit our website or interact with our services, we may automatically collect data about your device, such as:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Device type</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Operating system</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Unique device identifiers</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Device settings</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Geo-location data</li>
                    </ul>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Data we collect can depend on the individual settings of your device and software. We recommend checking the policies of your device manufacturer or software provider to learn what information they make available to us.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Personal Information</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may ask for personal information — for example, when you submit content to us or when you contact us — which may include one or more of the following:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Name</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Email</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Social media profiles</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Date of birth</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Phone/mobile number</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Home/mailing address</li>
                    </ul>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">User-Generated Content</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We consider “user-generated content” to be materials (text, image and/or video content) voluntarily supplied to us by our users for the purpose of publication on our website or re-publishing on our social media channels. All user-generated content is associated with the account or email address used to submit the materials.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Please be aware that any content you submit for the purpose of publication will be public after posting (and subsequent review or vetting process). Once published, it may be accessible to third parties not covered under this privacy policy.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Legitimate Reasons for Processing Your Personal Information</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We only collect and use your personal information when we have a legitimate reason for doing so. In which instance, we only collect personal information that is reasonably necessary to provide our services to you.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Collection and Use of Information</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may collect personal information from you when you do any of the following on our website:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Register for an account</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Enter any of our competitions, contests, sweepstakes, and surveys</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Sign up to receive updates from us via email or social media channels</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Use a mobile device or web browser to access our content</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Contact us via email, social media, or on any similar technologies</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When you mention us on social media</li>
                    </ul>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may collect, hold, use, and disclose information for the following purposes, and personal information will not be further processed in a manner that is incompatible with these purposes:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to provide you with our platform&#39;s core features and services</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to enable you to customise or personalise your experience of our website</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to deliver products and/or services to you</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to contact and communicate with you</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>for analytics, market research, and business development, including to operate and improve our website, associated applications, and associated social media platforms</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>for advertising and marketing, including to send you promotional information about our products and services and information about third parties that we consider may be of interest to you</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to consider your employment application</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to enable you to access and use our website, associated applications, and associated social media platforms</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>for internal record keeping and administrative purposes</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to run competitions, sweepstakes, and/or offer additional benefits to you</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to comply with our legal obligations and resolve any disputes that we may have</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>to attribute any content (e.g. posts and comments) you submit that we publish on our website</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>for security and fraud prevention, and to ensure that our sites and apps are safe, secure, and used in line with our terms of use</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>for technical assessment, including to operate and improve our app, associated applications, and associated social media platforms</li>
                    </ul>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may combine voluntarily provided and automatically collected personal information with general information or research data we receive from other trusted sources. For example, Our marketing and market research activities may uncover data and insights, which we may combine with information about how visitors use our site to improve our site and your experience on it.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Security of Your Personal Information</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When we collect and process personal information, and while we retain this information, we will protect it within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Although we will do our best to protect the personal information you provide to us, we advise that no method of electronic transmission or storage is 100% secure and no one can guarantee absolute data security.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>You are responsible for selecting any password and its overall security strength, ensuring the security of your own information within the bounds of our services. For example, ensuring any passwords associated with accessing your personal information and accounts are secure and confidential.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">How Long We Keep Your Personal Information</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We keep your personal information only for as long as we need to. This time period may depend on what we are using your information for, in accordance with this privacy policy. For example, if you have provided us with personal information as part of creating an account with us, we may retain this information for the duration your account exists on our system. If your personal information is no longer required for this purpose, we will delete it or make it anonymous by removing all details that identify you.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>However, if necessary, we may retain your personal information for our compliance with a legal, accounting, or reporting obligation or for archiving purposes in the public interest, scientific, or historical research purposes or statistical purposes.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Children’s Privacy</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We do not aim any of our products or services directly at children under the age of 13 and we do not knowingly collect personal information about children under 13.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Disclosure of Personal Information to Third Parties</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may disclose personal information to:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>a parent, subsidiary or affiliate of our company</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>third-party service providers for the purpose of enabling them to provide their services, including (without limitation) IT service providers, data storage, hosting and server providers, ad networks, analytics, error loggers, debt collectors, maintenance or problem-solving providers, marketingoradvertising providers, professional advisors, and payment systems operators</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>our employees, contractors, and/or related entities</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>our existing or potential agents or business partners</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>sponsors or promoters of any competition, sweepstakes, or promotion we run</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>credit reporting agencies, courts, tribunals, and regulatory authorities, in the event you fail to pay for goods or services we have provided to you</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>courts, tribunals, regulatory authorities, and law enforcement officers, as required by law, in connection with any actual or prospective legal proceedings, or in order to establish, exercise, or defend our legal rights</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>third parties, including agents or sub-contractors who assist us in providing information, products, services, or direct marketing to you</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>third parties to collect and process data</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>an entity that buys, or to which we transfer all or substantially all of our assets and business</li>
                    </ul>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Third parties we currently use include:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Google Analytics</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>MailChimp</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Google AdSense</li>
                    </ul>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">International Transfers of Personal Information</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The personal information we collect is stored and/or processed in United Kingdom, or where we or our partners, affiliates, and third-party providers maintain facilities.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The countries to which we store, process, or transfer your personal information may not have the same data protection laws as the country in which you initially provided the information. If we transfer your personal information to third parties in other countries: (i) we will perform those transfers in accordance with the requirements of applicable law; and (ii) we will protect the transferred personal information in accordance with this privacy policy.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Your Rights and Controlling Your Personal Information</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Your choice:</strong> By providing personal information to us, you understand we will collect, hold, use, and disclose your personal information in accordance with this privacy policy. You do not have to provide personal information to us, however, if you do not, it may affect your use of our website or the products and/or services offered on or through it.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Information from third parties:</strong> If we receive personal information about you from a third party, we will protect it as set out in this privacy policy. If you are a third party providing personal information about somebody else, you represent and warrant that you have such person’s consent to provide the personal information to us.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Marketing permission:</strong> If you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by contacting us using the details below.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Access:</strong> You may request details of the personal information that we hold about you.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Correction:</strong> If you believe that any information we hold about you is inaccurate, out of date, incomplete, irrelevant, or misleading, please contact us using the details provided in this privacy policy. We will take reasonable steps to correct any information found to be inaccurate, incomplete, misleading, or out of date.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Non-discrimination:</strong> We will not discriminate against you for exercising any of your rights over your personal information. Unless your personal information is required to provide you with a particular service or offer (for example providing user support), we will not deny you goods or services and/or charge you different prices or rates for goods or services, including through granting discounts or other benefits, or imposing penalties, or provide you with a different level or quality of goods or services.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Notification of data breaches:</strong> We will comply with laws applicable to us in respect of any data breach.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Complaints:</strong> If you believe that we have breached a relevant data protection law and wish to make a complaint, please contact us using the details below and provide us with full details of the alleged breach. We will promptly investigate your complaint and respond to you, in writing, setting out the outcome of our investigation and the steps we will take to deal with your complaint. You also have the right to contact a regulatory body or data protection authority in relation to your complaint.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Unsubscribe:</strong> To unsubscribe from our email database or opt-out of communications (including marketing communications), please contact us using the details provided in this privacy policy, or opt-out using the opt-out facilities provided in the communication. We may need to request specific information from you to help us confirm your identity.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Use of Cookies</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We use &quot;cookies&quot; to collect information about you and your activity across our site. A cookie is a small piece of data that our website stores on your computer, and accesses each time you visit, so we can understand how you use our site. This helps us serve you content based on preferences you have specified.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Please refer to our Cookie Policy for more information.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Business Transfers</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If we or our assets are acquired, or in the unlikely event that we go out of business or enter bankruptcy, we would include data, including your personal information, among the assets transferred to any parties who acquire us. You acknowledge that such transfers may occur, and that any parties who acquire us may, to the extent permitted by applicable law, continue to use your personal information according to this policy, which they will be required to assume as it is the basis for any ownership or use rights we have over such information.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Limits of Our Policy</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and policies of those sites, and cannot accept responsibility or liability for their respective privacy practices.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Changes to This Policy</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>At our discretion, we may change our privacy policy to reflect updates to our business processes, current acceptable practices, or legislative or regulatory changes. If we decide to change this privacy policy, we will post the changes here at the same link by which you are accessing this privacy policy.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If the changes are significant, or if required by applicable law, we will contact you (based on your selected preferences for communications from us) and all our registered users with the new details and links to the updated or changed policy.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If required by law, we will get your permission or give you the opportunity to opt in to or opt out of, as applicable, any new uses of your personal information.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Additional Disclosures for General Data Protection Regulation (GDPR) Compliance (EU)</h3>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Data Controller / Data Processor</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The GDPR distinguishes between organisations that process personal information for their own purposes (known as &quot;data controllers&quot;) and organisations that process personal information on behalf of other organisations (known as &quot;data processors&quot;). We, Reborngreen Ltd, located at the address provided in our Contact Us section, are a Data Controller with respect to the personal information you provide to us.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Legal Bases for Processing Your Personal Information</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We will only collect and use your personal information when we have a legal right to do so. In which case, we will collect and use your personal information lawfully, fairly, and in a transparent manner. If we seek your consent to process your personal information, and you are under 16 years of age, we will seek your parent or legal guardian’s consent to process your personal information for that specific purpose.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Our lawful bases depend on the services you use and how you use them. This means we only collect and use your information on the following grounds:</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Consent From You</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where you give us consent to collect and use your personal information for a specific purpose. You may withdraw your consent at any time using the facilities we provide; however this will not affect any use of your information that has already taken place. You may consent to providing your name and contact details for the purpose of entering a giveaway or promotion. While you may withdraw your entry at any time, this will not affect any selection or judging that has already taken place. If you have any further enquiries about how to withdraw your consent, please feel free to enquire using the details provided in the Contact Us section of this privacy policy.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Performance of a Contract or Transaction</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where you have entered into a contract or transaction with us, or in order to take preparatory steps prior to our entering into a contract or transaction with you. For example, if you contact us with an enquiry, we may require personal information such as your name and contact details in order to respond.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Our Legitimate Interests</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where we assess it is necessary for our legitimate interests, such as for us to provide, operate, improve and communicate our services. We consider our legitimate interests to include research and development, understanding our audience, marketing and promoting our services, measures taken to operate our services efficiently, marketing analysis, and measures taken to protect our legal rights and interests.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Compliance with Law</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>In some cases, we may have a legal obligation to use or keep your personal information. Such cases may include (but are not limited to) court orders, criminal investigations, government requests, and regulatory obligations. If you have any further enquiries about how we retain personal information in order to comply with the law, please feel free to enquire using the details provided in the Contact Us section of this privacy policy.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">International Transfers Outside of the European Economic Area (EEA)</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We will ensure that any transfer of personal information from countries in the European Economic Area (EEA) to countries outside the EEA will be protected by appropriate safeguards, for example by using standard data protection clauses approved by the European Commission, or the use of binding corporate rules or other legally accepted means.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Your Rights and Controlling Your Personal Information</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Restrict:</strong> You have the right to request that we restrict the processing of your personal information if (i) you are concerned about the accuracy of your personal information; (ii) you believe your personal information has been unlawfully processed; (iii) you need us to maintain the personal information solely for the purpose of a legal claim; or (iv) we are in the process of considering your objection in relation to processing on the basis of legitimate interests.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Objecting to processing:</strong> You have the right to object to processing of your personal information that is based on our legitimate interests or public interest. If this is done, we must provide compelling legitimate grounds for the processing which overrides your interests, rights, and freedoms, in order to proceed with the processing of your personal information.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Data portability:</strong> You may have the right to request a copy of the personal information we hold about you. Where possible, we will provide this information in CSV format or other easily readable machine format. You may also have the right to request that we transfer this personal information to a third party.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Additional Disclosures for UK General Data Protection Regulation (UK GDPR) Compliance (UK)</h3>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Data Controller / Data Processor</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The GDPR distinguishes between organisations that process personal information for their own purposes (known as “data controllers”) and organizations that process personal information on behalf of other organizations (known as “data processors”). For the purposes covered by this Privacy Policy, we are a Data Controller with respect to the personal information you provide to us and remain compliant with our data controller obligations under GDPR.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Third-Party Provided Content</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may indirectly collect personal information about you from third-parties who have your permission to share it. For example, if you purchase a product or service from a business working with us, and give your permission for us to use your details in order to complete the transaction.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may also collect publicly available information about you, such as from any social media and messaging platforms you may use. The availability of this information will depend on both the privacy policies and your own privacy settings on such platforms.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Additional Disclosure for Collection and Use of Personal Information</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>In addition to the aforementioned purposes warranting the collection and use of personal information, we may also conduct marketing and market research activities, including how visitors use our site, website improvement opportunities and user experience.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Personal Information No Longer Required for Our Purposes</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If your personal information is no longer required for our stated purposes, or if you instruct us under your Data Subject Rights, we will delete it or make it anonymous by removing all details that identify you (“Anonymisation”). However, if necessary, we may retain your personal information for our compliance with a legal, accounting, or reporting obligation or for archiving purposes in the public interest, scientific, or historical research purposes or statistical purposes.</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Legal Bases for Processing Your Personal Information</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Data Protection and Privacy Laws permit us to collect and use your personal data on a limited number of grounds. In which case, we will collect and use your personal information lawfully, fairly and in a transparent manner. We never directly market to any person(s) under 18 years of age.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Our lawful bases depend on the services you use and how you use them. This is a non-exhaustive list of the lawful bases we use:</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Consent From You</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where you give us consent to collect and use your personal information for a specific purpose. You may withdraw your consent at any time using the facilities we provide; however this will not affect any use of your information that has already taken place. When you contact us, we assume your consent based on your positive action of contact, therefore you consent to your name and email address being used so we can respond to your enquiry.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where you agree to receive marketing communications from us, we will do so based solely on your indication of consent or until you instruct us not to, which you can do at any time.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>While you may request that we delete your contact details at any time, we cannot recall any email we have already sent. If you have any further enquiries about how to withdraw your consent, please feel free to enquire using the details provided in the Contact Us section of this privacy policy.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Performance of a Contract or Transaction</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where you have entered into a contract or transaction with us, or in order to take preparatory steps prior to our entering into a contract or transaction with you. For example, if you contact us with an enquiry, we may require personal information such as your name and contact details in order to respond.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Our Legitimate Interests</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Where we assess it is necessary for our legitimate interests, such as for us to provide, operate, improve and communicate our services. We consider our legitimate interests to include research and development, understanding our audience, marketing and promoting our services, measures taken to operate our services efficiently, marketing analysis, and measures taken to protect our legal rights and interests.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Compliance with Law</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>In some cases, we may have a legal obligation to use or keep your personal information. Such cases may include (but are not limited to) court orders, criminal investigations, government requests, and regulatory obligations. For example, we are required to keep financial records for a period of 7 years. If you have any further enquiries about how we retain personal information in order to comply with the law, please feel free to enquire using the details provided in the Contact Us section of this privacy policy.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">International Transfers of Personal Information</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The personal information we collect is stored and/or processed in the United Kingdom by us. Following an adequacy decision by the EU Commission, the UK has been granted an essentially equivalent level of protection to that guaranteed under UK GDPR.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>On some occasions, where we share your data with third parties, they may be based outside of the UK, or the European Economic Area (“EEA”). These countries to which we store, process, or transfer your personal information may not have the same data protection laws as the country in which you initially provided the information.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If we transfer your personal information to third parties in other countries:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>we will perform those transfers in accordance with the requirements of the UK GDPR (Article 45) and Data Protection Act 2018;</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>we will adopt appropriate safeguards for protecting the transferred data, including in transit, such as standard contractual clauses (“SCCs”) or binding corporate rules.</li>
                    </ul>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Your Data Subject Rights</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right to Restrict Processing:</strong> You have the right to request that we restrict the processing of your personal information if (i) you are concerned about the accuracy of your personal information; (ii) you believe your personal information has been unlawfully processed; (iii) you need us to maintain the personal information solely for the purpose of a legal claim; or (iv) we are in the process of considering your objection in relation to processing on the basis of legitimate interests.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right to Object:</strong> You have the right to object to processing of your personal information that is based on our legitimate interests or public interest. If this is done, we must provide compelling legitimate grounds for the processing which overrides your interests, rights, and freedoms, in order to proceed with the processing of your personal information.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right to be Informed:</strong> You have the right to be informed with how your data is collected, processed, shared and stored.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right of Access:</strong> You may request a copy of the personal information that we hold about you at any time by submitting a Data Subject Access Request (DSAR). The statutory deadline for fulfilling a DSAR request is 30 calendar days from our receipt of your request.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right to Erasure:</strong> In certain circumstances, you can ask for your personal data to be erased from the records held by organisations. However this is a qualified right; it is not absolute, and may only apply in certain circumstances.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When may the right to erasure apply?</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When the personal data is no longer necessary for the purpose for which it was originally collected or processed for.</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If consent was the lawful basis for processing personal data and that consent has been withdrawn. Reborngreen Ltd relies on consent to process personal data in very few circumstances.</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The Company is relying on legitimate interests as a legal basis for processing personal data and an individual has exercised the right to object and it has been determined that the Company has no overriding legitimate grounds to refuse that request.</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Personal data are being processed for direct marketing purposes e.g. a person’s name and email address, and the individual objects to that processing.</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>There is legislation that requires that personal data are to be destroyed.</li>
                    </ul>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right to Portability:</strong> Individuals have the right to get some of their personal data from an organisation in a way that is accessible and machine-readable, for example as a csv file. Associated with this, individuals also have the right to ask an organisation to transfer their personal data to another organisation.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>However, the right to portability:</p>
                    <ul>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>only applies to personal data which a person has directly given to Reborngreen Ltd in electronic form; and</li>
                         <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>onward transfer will only be available where this is “technically feasible”.</li>
                    </ul>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Right to Rectification:</strong> If personal data is inaccurate, out of date, or incomplete, individuals have the right to correct, update or complete that data. Collectively this is referred to as the right to rectification. Rectification may involve filling the gaps i.e. to have to have incomplete personal data completed – although this will depend on the purposes for the processing. This may involve adding a supplementary statement to the incomplete data to highlight any inaccuracy or claim thereof.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>This right only applies to an individual’s own personal data; a person cannot seek the rectification of another person’s information.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Notification of data breaches:</strong> Upon discovery of a data breach, we will investigate the incident and report it to the UK’s data protection regulator and yourself, if we deem it appropriate to do so.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'><strong>Complaints:</strong> You have the right, at any time, to lodge a complaint with the Information Commissioner&#39;s Office (ICO), the UK supervisory authority for data protection issues (www.ico.org.uk). We would, however, appreciate the chance to deal with your concerns before you approach the ICO so please contact us in the first instance using the details below. Please provide us with as much information as you can about the alleged breach. We will promptly investigate your complaint and respond to you, in writing, setting out the outcome of our investigation and the steps we will take to deal with your complaint.</p>
                     <h4 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Enquiries, Reports and Escalation</h4>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>To enquire about Reborngreen Ltd&#39;s privacy policy, or to report violations of user privacy, you may contact our Data Protection Officer using the details in the Contact us section of this privacy policy.</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If we fail to resolve your concern to your satisfaction, you may also contact the Information Commissioner&#39;s Office (ICO), the UK Data Protection regulator:</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Information Commissioner&#39;s Office <br />
                        Wycliffe House <br />
                        Water Lane <br />
                        Wilmslow <br />
                        Cheshire <br />
                        SK9 5AF <br />
                        <br />
                        Tel: 0303 123 1113 (local rate) <br />
                        Website: www.ico.org.uk</p>
                    <h3 className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Contact Us</h3>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>For any questions or concerns regarding your privacy, you may contact us using the following details:</p>
                     <p  className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Dan Soldan<br />
                        dan@reborngreen.co.uk</p>

                </div>

            </section>

        </div>
    )
}

export default page