import Link from 'next/link'
import React from 'react'

const page = () => {
    return (
        <div className='overflow-hidden h-full'>

            <section className='w-full flex items-center justify-start flex-col bg-[#fbfbfb] mt-10 max-w-[1800px] mb-[60px]  px-[30px] lg:px-[60px] xll:px-[120px] py-[4rem] mx-auto'>
                <h1 className='text-center mb-[20px] font-poppins text-[30px] xsm:text-[40px] lg:text-[55px] xll:text-[60px] font-[500] text-[#3d3d3d]'>
                Terms of Service
                </h1>

                <div className='privacy-text'>
                <h2 className=" text-2xl xsm:text-3xl sm:text-4xl text-left font-poppins text-[#222] mb-3">Terms of Service</h2>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>These Terms of Service govern your use of the website located at&#39;&#39;<Link href="https://reborngreen.org">https://reborngreen.org</Link>&#39;&#39;;and any related services provided by Reborngreen Ltd.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>By accessing&nbsp;<Link href="https://reborngreen.org">https://reborngreen.org</Link>, you agree to abide by these Terms of Service and to comply with all applicable laws and regulations. If you do not agree with these Terms of Service, you are prohibited from using or accessing this website or using any other services provided by Reborngreen Ltd.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We, Reborngreen Ltd, reserve the right to review and amend any of these Terms of Service at our sole discretion. Upon doing so, we will update this page. Any changes to these Terms of Service will take effect immediately from the date of publication.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>These Terms of Service were last updated on March 31, 2024.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Service Description</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Reborngreen Ltd is dedicated to environmental sustainability through strategic reforestation, carbon offsetting, and supporting community and animal welfare projects. The service includes providing individuals and businesses with opportunities to contribute to these initiatives through financial or participatory means.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Limitations of Use</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>By using this website, you warrant on behalf of yourself, your users, and other parties you represent that you will not:</p>
                    <ul>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>modify, copy, prepare derivative works of, decompile, or reverse engineer any materials and software contained on this website;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>remove any copyright or other proprietary notations from any materials and software on this website;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>transfer the materials to another person or 	&bdquo;mirror&bdquo; the materials on any other server;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>knowingly or negligently use this website or any of its associated services in a way that abuses or disrupts our networks or any other service Reborngreen Ltd provides;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>use this website or its associated services to transmit or publish any harassing, indecent, obscene, fraudulent, or unlawful material;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>use this website or its associated services in violation of any applicable laws or regulations;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>use this website in conjunction with sending unauthorised advertising or spam;</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>harvest, collect, or gather user data without the user&rsquo;s consent; or</li>
                        <li className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>use this website or its associated services in such a way that may infringe the privacy, intellectual property rights, or other rights of third parties.</li>
                    </ul>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Intellectual Property</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The intellectual property in the materials contained in this website are owned by or licensed to Reborngreen Ltd and are protected by applicable copyright and trademark law. We grant our users permission to download one copy of the materials for personal, non-commercial transitory use.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>This constitutes the grant of a licence, not a transfer of title. This licence shall automatically terminate if you violate any of these restrictions or the Terms of Service, and may be terminated by Reborngreen Ltd at any time.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">User-Generated Content</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>You retain your intellectual property ownership rights over content you submit to us for publication on our website. We will never claim ownership of your content, but we do require a licence from you in order to use it.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>When you use our website or its associated services to post, upload, share, or otherwise transmit content covered by intellectual property rights, you grant to us a non-exclusive, royalty-free, transferable, sub-licensable, worldwide licence to use, distribute, modify, run, copy, publicly display, translate, or otherwise create derivative works of your content in a manner that is consistent with your privacy preferences and our Privacy Policy.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The licence you grant us can be terminated at any time by deleting your content or account. However, to the extent that we (or our partners) have used your content in connection with commercial or sponsored content, the licence will continue until the relevant commercial or post has been discontinued by us.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>You give us permission to use your username and other identifying information associated with your account in a manner that is consistent with your privacy preferences and our Privacy Policy.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">User Obligations</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Users agree to use Reborngreen Ltd&#39;s services for lawful purposes only and in a manner that does not infringe the rights of, or restrict or inhibit the use and enjoyment of the service by any third party. This includes conduct which is unlawful, or which may harass or cause distress or inconvenience to any person.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Registration and Payments</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>In order to use our services you need to create an account. Any information provided needs to be accurate and updated if necessary. Customers are liable for maintaining their accounts and are fully responsible for all activities occurring under their accounts. Should anybody gain unauthorised access to your account, you need to notify us immediately. Reborngreen Ltd is not liable for any loss or damage arising from failure to maintain the confidentiality of your account. When creating your account, you are required to provide your financial information relevant to the chosen payment method; in some cases, you may be requested to provide your credit card details.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Disclaimer and Limitations of Liability</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The website of Reborngreen Ltd and the materials provided therein are offered on an &#39;as is&#39; and &#39;as available&#39; basis without any warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. Reborngreen Ltd makes no warranty that the information, materials, products, or services included on or otherwise made available to you through the website are free of viruses or other harmful components.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Reborngreen Ltd, its directors, employees, agents, suppliers, or affiliates, shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the services; any conduct or content of any third party on the services; any content obtained from the services, including errors or omissions; unauthorised access, use, or alteration of your transmissions or content; the use or display of any content or the interactions or transactions with any website users, whether based on warranty, contract, tort (including negligence), or any other legal theory, even if Reborngreen Ltd has been advised of the possibility of such damages.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Furthermore, Reborngreen Ltd shall not be liable for any loss or damage arising from your failure to comply with this section or from any content posted on Reborngreen Ltd&#39;s services, whether online or offline. This includes, but is not limited to, the transmission of any disabling device or viruses which may infect your equipment, failure of mechanical or electronic equipment or communication lines, telephone or other interconnect problems, unauthorised access, theft, operator errors, severe weather, earthquakes, natural disasters, strikes or other labour problems, wars, or governmental restrictions.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>In the context of this agreement, &#39;&#39;consequential loss&#39;&#39; encompasses any consequential loss, indirect loss, real or anticipated loss of profit, loss of benefit, loss of revenue, loss of business, loss of goodwill, loss of opportunity, loss of savings, loss of reputation, loss or corruption of data, or any other non-direct loss, whether under statute, contract, equity, tort (including negligence), indemnity, or otherwise.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Due to the nature of the internet and electronic communications, Reborngreen Ltd does not warrant that access to, or the operation of, its website will be uninterrupted or error-free, that defects will be corrected, or that the site or the server that makes it available are free of viruses or other harmful components.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Because certain jurisdictions do not allow some of the exclusions or limitations as set forth above, some of these exclusions and limitations may not apply to you. In such jurisdictions, Reborngreen Ltd&#39;s liability is limited and warranties are excluded to the greatest extent permitted by law. Users are responsible for ensuring that they are legally allowed to enter into this agreement and use the services of Reborngreen Ltd within their jurisdiction.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Accuracy of Materials</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>The materials provided on the Reborngreen Ltd website are presented for general informational purposes only and should not be considered exhaustive or relied upon as the sole basis for making decisions. While Reborngreen Ltd endeavours to ensure the accuracy and reliability of the information provided on its website, it does not guarantee the correctness, completeness, or up-to-date nature of the materials or any linked resources. Given the specific focus of Reborngreen Ltd on environmental sustainability and reforestation efforts, the complexity of these topics means that the information provided may require periodic updates and revisions to reflect new research, developments, and practices in the field.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Users are encouraged to consult additional sources of information and, if necessary, seek professional advice before making decisions based on the information found on the Reborngreen Ltd website. Reliance on the materials provided on the website is at the user&#39;s own risk. Reborngreen Ltd reserves the right to make changes to the content of its website at any time without prior notification. It is the responsibility of users to regularly review the website to stay informed of any updates or modifications to the information provided.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Additional Tools</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Please note that our website may include third-party tools which are outside of our control. The access to said tools is provided on an &#39;as is&#39; basis with no warranties, expressed or implied, and without any endorsement. We are not liable for the use of the third-party tools provided on our website. You are solely responsible for any risks associated with using said tools, we recommend reading the relevant third-party provider&rsquo;s Terms of Service. Reborngreen Ltd has the right to offer new third-party tools in the future.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Links</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Reborngreen Ltd has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement, approval or control by Reborngreen Ltd of the site. Use of any such linked site is at your own risk and we strongly advise you make your own investigations with respect to the suitability of those sites.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Inaccuracies and Mistakes</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Please note that any content available on our website may contain typographical errors, inaccuracies, or mistakes related to the service&rsquo;s description, pricing, promotion, and availability. We have the right to cancel or update any existing orders should any information provided by us be proven inaccurate. Said information can be amended at any time without prior notice. Please note that we are not obligated to clarify any of the information related to our website and service, including pricing information, except as required by law.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Indemnification</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys&rsquo; fees and expenses, made by any third party due to or arising out of: (1) your Contributions; (2) use of the website; (3) breach of these Terms of Service; (4) any breach of your representations and warranties set forth in these Terms of Service; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the website with whom you connected via the website.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defence and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defence of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Right to Terminate</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>We may suspend or terminate your right to use our website and terminate these Terms of Service immediately upon written notice to you for any breach of these Terms of Service.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Severance</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>Any term of these Terms of Service which is wholly or partially void or unenforceable is severed to the extent that it is void or unenforceable. The validity of the remainder of these Terms of Service is not affected.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Entire Agreement</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>These Terms of Service and any policies or operating rules posted by us on the website or with respect to the website constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms of Service shall not operate as a waiver of such right or provision. These Terms of Service operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control.</p>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>If any provision or part of a provision of these Terms of Service is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Service and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment, or agency relationship created between you and us as a result of these Terms of Service or use of the website. You agree that these Terms of Service will not be construed against us by virtue of having drafted them. You hereby waive any and all defences you may have based on the electronic form of these Terms of Service and the lack of signing by the parties hereto to execute these Terms of Service.</p>
                    <h3  className=" text-2xl text-left md:text-3xl mdd:text-4xl font-worksan text-[#222] mb-1 mt-6">Governing Law</h3>
                    <p className=' text-sm sm:text-[16px font-poppins tracking-wider text-[#2c2c2c] px-0 xsm:px-[10px] text-left'>These Terms of Service are governed by and construed in accordance with the laws of the United Kingdom. You irrevocably submit to the exclusive jurisdiction of the courts in that location.</p>
                </div>
            </section>

        </div>
    )
}

export default page